path=r"C:\Users\raund\Desktop\portfolio\Medpremium\app\clinic\booking\pay\[appointmentId]\page.tsx"
c=[]
c.append("'use client'")
c.append("import { useState, useEffect } from 'react'")
c.append("import { useRouter } from 'next/navigation'")
c.append("import Link from 'next/link'")
print("done")
c.append("")
c.append("export default function PaymentPage({ params }: { params: { appointmentId: string } }) {")
c.append("  const router = useRouter()")
c.append("  const [appointment, setAppointment] = useState<any>(null)")
c.append("  const [paying, setPaying] = useState(false)")
c.append("  const [paid, setPaid] = useState(false)")
c.append("")
c.append("  useEffect(() => {")
c.append("    fetch(`/api/clinic/appointments/\x60)")
c.append("      .then(r => r.json()).then(setAppointment)")
c.append("  }, [params.appointmentId])")
c.append("")
c.append("  function handlePay() {")
c.append("    setPaying(true)")
c.append("    setTimeout(() => { setPaid(true); setPaying(false) }, 3000)")
c.append("  }")
c.append("")
c.append("  if (paid) return (")
c.append("    <div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',background:'linear-gradient(180deg,#dce8f2,#eef3f8)'}}>")
c.append("      <div style={{background:'#fff',borderRadius:'24px',padding:'48px',textAlign:'center',boxShadow:'0 25px 70px rgba(40,55,80,.14)'}}>")
c.append("        <div style={{fontSize:'64px',marginBottom:'16px'}}>✅</div>")
c.append("        <h2 style={{fontSize:'28px',fontWeight:700,color:'#24344A',marginBottom:'12px'}}>Оплата принята!</h2>")
c.append("        <p style={{color:'#607089',marginBottom:'32px'}}>Ваша запись подтверждена. Ждём вас в клинике!</p>")
c.append("        <Link href='/clinic/dashboard' style={{background:'linear-gradient(135deg,#54719A,#435C7D)',color:'#fff',padding:'14px 32px',borderRadius:'14px',fontWeight:600,textDecoration:'none'}}>Перейти в личный кабинет</Link>")
c.append("      </div>")
c.append("    </div>")
c.append("  )")
c.append("")
c.append("  if (!appointment) return <div style={{padding:'48px',textAlign:'center'}}>Загрузка...</div>")
c.append("")
c.append("  const date = new Date(appointment.timeSlot?.startTime).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})")
c.append("  const time = new Date(appointment.timeSlot?.startTime).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})")
c.append("")
c.append("  return (")
c.append("    <div style={{minHeight:'100vh',background:'linear-gradient(180deg,#dce8f2,#eef3f8)',display:'flex',alignItems:'center',justifyContent:'center',padding:'24px'}}>")
c.append("      <div style={{background:'#fff',borderRadius:'24px',padding:'40px',maxWidth:'560px',width:'100%',boxShadow:'0 25px 70px rgba(40,55,80,.14)'}}>")
c.append("        <h1 style={{fontSize:'28px',fontWeight:700,color:'#0f2238',marginBottom:'24px'}}>Оплата приёма</h1>")
c.append("        <div style={{marginBottom:'24px'}}>")
c.append("          {[['Врач',appointment.doctor?.user?.name],['Услуга',appointment.service?.name],['Дата',date],['Время',time],['Пациент',appointment.patientName]].map(([l,v])=>(")
c.append("            <div key={l} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid #f0f4f8'}}>")
c.append("              <span style={{color:'#607089'}}>{l}</span>")
c.append("              <span style={{fontWeight:600,color:'#24344A'}}>{v}</span>")
c.append("            </div>")
c.append("          ))}")
c.append("          <div style={{display:'flex',justifyContent:'space-between',padding:'16px',background:'#f0f7ff',borderRadius:'12px',marginTop:'12px'}}>")
c.append("            <span style={{fontWeight:600}}>К оплате</span>")
c.append("            <span style={{fontWeight:700,fontSize:'20px',color:'#2563eb'}}>{appointment.totalAmount?.toLocaleString('ru-RU')} ₽</span>")
c.append("          </div>")
c.append("        </div>")
c.append("        <button onClick={handlePay} disabled={paying} style={{width:'100%',height:'56px',borderRadius:'14px',background:paying?'#94a3b8':'linear-gradient(135deg,#54719A,#435C7D)',color:'#fff',fontSize:'18px',fontWeight:600,border:'none',cursor:paying?'not-allowed':'pointer',marginBottom:'16px'}}>")
c.append("          {paying ? 'Обработка платежа...' : `Оплатить \ ₽`}")
c.append("        </button>")
c.append("        <div style={{textAlign:'center'}}>")
c.append("          <Link href='/clinic/dashboard' style={{color:'#2563eb',fontWeight:500}}>Перейти в личный кабинет →</Link>")
c.append("        </div>")
c.append("      </div>")
c.append("    </div>")
open(path,chr(119),encoding=chr(117)+chr(116)+chr(102)+chr(45)+chr(56)).write(chr(10).join(c))
c.append("}")
